name: finapi
channels:
  - defaults
dependencies:
  - python=3.11
  - black
  - conda-forge::yfinance
  - conda-forge::pydantic
  - conda-forge::fastapi
  - anaconda::pandas
  - conda-forge::uvicorn
  - conda-forge::httpx
  - conda-forge::pytest
